"""Unit tests for the model file version stamp (``common.utils.model_version``).

XGBoost warns whenever a pickled model is loaded by a version other than the
one that wrote it. It fires on any difference at all, patch releases included,
and in both directions, and it says nothing about which side is older. Only one
direction matters: measured over every pair of six releases (2.1.4 to 3.4.0),
loading into a newer XGBoost reproduced the trained predictions bitwise, while
loading into an older one moved scores by up to 0.076 and flipped 21 of 2,000
labels at a 0.5 threshold without failing.

Telling the two apart needs the writing version, which is not recoverable from
the loaded model, so it is stamped on at save time. These tests cover the stamp
surviving a real round trip, the three outcomes it produces (note, warning, and
the unstamped fallback), and the warnings the loader must leave alone.

The mismatch itself is provoked by replacing ``joblib.load``: pinning a fixture
to an XGBoost old enough to trigger the real warning would make the tests
expire the next time the pin moves.
"""

import warnings

import joblib
import pytest
import xgboost as xgb
from sklearn.neural_network import MLPClassifier

from aiqclib.common.utils import model_version
from aiqclib.common.utils.model_version import (
    STAMP_ATTRIBUTE,
    load_model_file,
    read_model_stamp,
    report_model_version,
    stamp_model_version,
)

#: The warning XGBoost emits, abridged after the actionable sentence.
XGBOOST_WARNING = (
    "[16:25:23] WARNING: /work/src/common/error_msg.h:83: If you are loading "
    "a serialized model (like pickle in Python, RDS in R) or configuration "
    "generated by an older version of XGBoost, please export the model by "
    "calling `Booster.save_model` from that version first, then load it back "
    "in current version."
)


@pytest.fixture
def unreported():
    """Clear the once-per-process record around a test.

    Module state by design, so without this the first test to report a given
    severity would silence every test after it, and the order would decide
    which ones pass.
    """
    model_version._reported.clear()
    yield
    model_version._reported.clear()


@pytest.fixture
def model(training_dir):
    """A real fitted XGBoost model, loaded from the training fixtures."""
    return joblib.load(str(training_dir / "model_temp_xgb.joblib"))


class TestStamping:
    """Recording the writing version where the reader can find it."""

    def test_an_xgboost_model_is_stamped(self, model):
        """The stamp is the installed version, not a constant."""
        assert stamp_model_version(model) == xgb.__version__
        assert read_model_stamp(model) == xgb.__version__

    def test_other_estimators_are_left_alone(self):
        """Only XGBoost raises the warning this answers.

        Stamping an sklearn estimator would record a version that has nothing
        to do with how that file loads.
        """
        other = MLPClassifier()
        assert stamp_model_version(other) is None
        assert not hasattr(other, STAMP_ATTRIBUTE)

    def test_none_is_tolerated(self):
        """A model that was never built must not break saving."""
        assert stamp_model_version(None) is None

    def test_the_stamp_survives_a_round_trip(self, model, tmp_path):
        """The point of the attribute: it has to come back out of the pickle."""
        stamp_model_version(model)
        path = tmp_path / "model.joblib"
        joblib.dump(model, path)

        assert read_model_stamp(joblib.load(path)) == xgb.__version__

    def test_a_stamped_model_still_predicts(self, model, tmp_path):
        """An extra attribute must not disturb the estimator itself.

        The stamp is set on a third-party object, so this pins that XGBoost
        neither rejects it nor changes behaviour because of it.
        """
        import numpy as np

        features = np.zeros((3, model.n_features_in_))
        before = model.predict_proba(features)

        stamp_model_version(model)
        path = tmp_path / "model.joblib"
        joblib.dump(model, path)
        after = joblib.load(path).predict_proba(features)

        assert np.array_equal(before, after)

    def test_re_saving_refreshes_the_stamp(self, model):
        """The stamp must describe the file, not the first save of the model."""
        model._aiqclib_xgboost_version = "1.0.0"
        stamp_model_version(model)
        assert read_model_stamp(model) == xgb.__version__

    def test_an_unstamped_model_reads_as_none(self):
        """Files written before stamping existed have to be recognizable.

        Built rather than loaded from a fixture: regenerating the fixtures
        with the current library would stamp them, and this case has to keep
        meaning "no stamp" after that happens.
        """
        assert read_model_stamp(xgb.XGBClassifier()) is None


class TestReportedSeverity:
    """The direction of the difference decides how loudly it is said."""

    def test_an_older_file_is_only_a_note(self, unreported, capsys):
        """The safe direction: this environment reproduces the predictions."""
        result = report_model_version("/models/temp.joblib", "0.0.1")

        assert result == "note"
        out = capsys.readouterr().out
        assert "note:" in out
        assert "0.0.1" in out and xgb.__version__ in out
        assert "Nothing to do" in out

    def test_a_note_is_not_a_warning(self, unreported):
        """Nothing is wrong, so nothing goes through :mod:`warnings`."""
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            assert report_model_version("/models/temp.joblib", "0.0.1") == "note"

    def test_the_same_version_is_only_a_note(self, unreported, capsys):
        """Equality cannot change predictions, whatever prompted the report."""
        assert report_model_version("/m.joblib", xgb.__version__) == "note"
        assert "note:" in capsys.readouterr().out

    def test_a_newer_file_warns(self, unreported):
        """The direction that changed predictions silently in testing."""
        with pytest.warns(UserWarning, match="older XGBoost") as record:
            assert report_model_version("/models/temp.joblib", "999.0.0") == "warning"

        message = str(record[0].message)
        assert "999.0.0" in message
        assert xgb.__version__ in message

    def test_the_warning_quantifies_the_risk(self, unreported):
        """A vague "may differ" is not actionable; the measured effect is."""
        with pytest.warns(UserWarning, match="flipped 21 of 2,000 labels"):
            report_model_version("/models/temp.joblib", "999.0.0")

    def test_the_warning_says_how_to_fix_it(self, unreported):
        """Upgrading this environment is the cheaper of the two remedies."""
        with pytest.warns(UserWarning, match="Upgrade this environment"):
            report_model_version("/models/temp.joblib", "999.0.0")

    def test_an_unstamped_file_warns_without_claiming_a_direction(self, unreported):
        """A file written before stamping cannot be judged, so it says so."""
        with pytest.warns(UserWarning, match="does not record which one") as record:
            assert report_model_version("/models/temp.joblib", None) == "unknown"

        assert "one direction only" in str(record[0].message)

    def test_an_unparseable_version_falls_back(self, unreported):
        """A development build gives no ordering, so none is assumed.

        Guessing here would be worse than admitting ignorance: calling a
        risky load safe is exactly the failure this whole mechanism exists to
        prevent.
        """
        with pytest.warns(UserWarning, match="cannot be judged"):
            result = report_model_version("/models/temp.joblib", "3.4.0.dev1")
        assert result == "unknown"

    def test_versions_compare_numerically_not_as_text(self):
        """3.10 is newer than 3.9, which a string comparison gets backwards.

        The trap is real rather than theoretical: XGBoost is at 3.4 and will
        reach 3.10, at which point a text comparison would start calling every
        newer file older and reporting a risky load as safe.
        """
        assert model_version._as_tuple("3.10.0") > model_version._as_tuple("3.9.0")
        assert "3.10.0" < "3.9.0", "string comparison orders these the wrong way"


class TestReportedOncePerRun:
    """Repetition per target and per dataset would bury the phase output."""

    def test_a_note_is_said_once(self, unreported, capsys):
        assert report_model_version("/a.joblib", "0.0.1") == "note"
        capsys.readouterr()
        assert report_model_version("/b.joblib", "0.0.1") == "repeat"
        assert capsys.readouterr().out == ""

    def test_a_warning_is_said_once(self, unreported):
        with pytest.warns(UserWarning):
            report_model_version("/a.joblib", "999.0.0")
        with warnings.catch_warnings(record=True) as second:
            warnings.simplefilter("always")
            assert report_model_version("/b.joblib", "999.0.0") == "repeat"
        assert second == []

    def test_a_note_does_not_silence_a_warning(self, unreported):
        """The severities are tracked apart, so the risky case is still heard.

        A run can load a mix: one model from an older environment and one from
        a newer. Sharing a single flag would let the harmless case suppress
        the one that changes predictions.
        """
        assert report_model_version("/a.joblib", "0.0.1") == "note"
        with pytest.warns(UserWarning, match="older XGBoost"):
            assert report_model_version("/b.joblib", "999.0.0") == "warning"


class TestLoadModelFile:
    """Catching XGBoost's complaint where the file name is still known."""

    @pytest.fixture
    def warning_load(self, monkeypatch, model):
        """Make the loader see a model pickled by another XGBoost."""

        def fake_load(file_name):
            warnings.warn(XGBOOST_WARNING, UserWarning)
            return model

        monkeypatch.setattr(model_version, "load", fake_load)
        return model

    def test_a_quiet_load_reports_nothing(self, unreported, training_dir):
        """The matching-version case, which is what most users have."""
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            loaded = load_model_file(str(training_dir / "model_temp_xgb.joblib"))
        assert isinstance(loaded, xgb.XGBClassifier)

    def test_a_stamped_model_is_reported_by_direction(
        self, unreported, warning_load, capsys
    ):
        """The stamp read back from the model decides the severity."""
        warning_load._aiqclib_xgboost_version = "0.0.1"
        with warnings.catch_warnings():
            warnings.simplefilter("error")
            load_model_file("/models/temp.joblib")
        assert "note:" in capsys.readouterr().out

    def test_an_unstamped_model_falls_back_to_the_warning(
        self, unreported, warning_load
    ):
        """Old model files keep the version-less message."""
        if hasattr(warning_load, STAMP_ATTRIBUTE):
            delattr(warning_load, STAMP_ATTRIBUTE)

        with pytest.warns(UserWarning, match="does not record which one"):
            load_model_file("/models/temp.joblib")

    def test_xgboosts_own_warning_is_replaced_not_repeated(
        self, unreported, warning_load
    ):
        """Restating means replacing; two copies would be worse than one."""
        with pytest.warns(UserWarning) as record:
            load_model_file("/models/temp.joblib")

        assert len(record) == 1
        assert "Booster.save_model" not in str(record[0].message)

    def test_other_warnings_are_re_emitted(self, unreported, monkeypatch, model):
        """Catching one warning must not swallow the rest.

        ``catch_warnings`` intercepts everything raised inside the block, so
        anything not recognized has to be put back deliberately.
        """

        def fake_load(file_name):
            warnings.warn("an unrelated remark", DeprecationWarning)
            return model

        monkeypatch.setattr(model_version, "load", fake_load)
        with pytest.warns(DeprecationWarning, match="unrelated"):
            load_model_file("/models/temp.joblib")

    def test_an_unrelated_xgboost_warning_passes_through(
        self, unreported, monkeypatch, model
    ):
        """Both markers must match, so other XGBoost logs are left alone.

        Every native XGBoost log line arrives through the same callback as a
        plain ``UserWarning``, so matching one loose fragment would restate
        messages that have nothing to do with serialization.
        """

        def fake_load(file_name):
            warnings.warn("[16:25:23] WARNING: No visible GPU is found", UserWarning)
            return model

        monkeypatch.setattr(model_version, "load", fake_load)
        with pytest.warns(UserWarning, match="No visible GPU"):
            load_model_file("/models/temp.joblib")

    def test_an_exception_still_propagates(self, unreported, monkeypatch):
        """A failed load is the bigger news; the block must not hide it."""

        def fake_load(file_name):
            warnings.warn(XGBOOST_WARNING, UserWarning)
            raise RuntimeError("corrupt model file")

        monkeypatch.setattr(model_version, "load", fake_load)
        with pytest.raises(RuntimeError, match="corrupt"):
            load_model_file("/models/temp.joblib")
